### ISSUE TITLE
Errors on the threat investigation iphyton code 

### ISSUE THREAD

**Issue by solrac901** [Open-Network-Insight/oni-oa#3]
http://XXXXXXXXXXXXXXX:8889/notebooks/user/20151115/Threat_Investigation_20151115.ipynb

Sending errors display_expanded_search variable / module is not defined,

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-b42ac8d332ec> in <module>()
----> 1 display_expanded_search()

NameError: name 'display_expanded_search' is not defined

**Comment by EverLoSa** [comment]
This issue was moved to "open-network-insight" issues.
